
export ELASTIC_END_POINT=""
export ELASTIC_CLOUD_ID=""
export ELASTIC_INDEX=""
export ELASTIC_USER_NAME=""
export ELASTIC_PASSWORD=""
export BUCKET_NAME=""
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
